[book]
title = "Bombolab"
authors = ["charfranr"]
description = "Forward Kinematics Visualizer for Robotic Arms"
language = "en"
src = "docs/src"

[build]
build-dir = "docs/book"

[output.html]
git-repository-url = "https://github.com/charfranr/bombolab"
edit-url-template = "https://github.com/charfranr/bombolab/edit/main/docs/src/{path}"
additional-css = []
additional-js = []
no-section-label = false

[output.html.fold]
enable = true
level = 1
