/**
 * CandidatesOverlay — debug visualization of the calibrator's circle
 * candidates, drawn ON the live scene so the user (or a future VLM pass)
 * can pick the semantic pivot by eye.
 *
 * Positions follow the exact renderer pipeline: world = F_k(q) × jaw ×
 * scale × cal × center, with the jaw term applied before scale×cal exactly
 * like StlRobotScene does. Loads web/public/calibration-candidates.json
 * (generated by `bun run scripts/calibrate.ts --candidates`).
 */

import { useEffect, useState } from 'react';
import * as THREE from 'three';
import { useFrame, useThree } from '@react-three/fiber';
import { Html } from '@react-three/drei';
import type { FramePose } from '../renderers/types';
import { STL_META } from '../renderers/stlMapping';

interface CandidateData {
  id: number;
  center: [number, number, number];
  radius: number;
  normal: [number, number, number];
}

interface CandidatesFile {
  version: number;
  parts: { filename: string; candidates: CandidateData[] }[];
}

interface Props {
  frames: FramePose[];
  gripper: number;
  calibrationConfigRef?: React.MutableRefObject<Map<string, THREE.Matrix4>>;
  calibrationOverridesRef?: React.MutableRefObject<Map<string, THREE.Matrix4>>;
  stlScaleRef?: React.MutableRefObject<number>;
}

/** Build a numbered sprite label. */
function labelSprite(text: string, color: string): THREE.Sprite {
  const canvas = document.createElement('canvas');
  canvas.width = 128;
  canvas.height = 64;
  const ctx = canvas.getContext('2d')!;
  ctx.clearRect(0, 0, 128, 64);
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.arc(64, 32, 26, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#fff';
  ctx.font = 'bold 34px monospace';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(text, 64, 34);
  const tex = new THREE.CanvasTexture(canvas);
  const mat = new THREE.SpriteMaterial({ map: tex, depthTest: false, transparent: true });
  const sprite = new THREE.Sprite(mat);
  sprite.scale.set(14, 7, 1);
  return sprite;
}

const PALETTE = ['#ff4444', '#44ff44', '#4488ff', '#ffaa00', '#ff44ff', '#44ffee', '#ffee44', '#ff8844', '#88ff44', '#4488ee', '#ee4488', '#aaff44'];

export default function CandidatesOverlay({ frames, gripper, calibrationConfigRef, calibrationOverridesRef, stlScaleRef }: Props) {
  const [data, setData] = useState<CandidatesFile | null>(null);
  const [group, setGroup] = useState<THREE.Group | null>(null);
  const [pickMode, setPickMode] = useState(false);
  const [anchor, setAnchor] = useState<[number, number, number] | null>(null);
  const { gl, scene, camera } = useThree();

  useEffect(() => {
    fetch('/calibration-candidates.json')
      .then((r) => (r.ok ? r.json() : null))
      .then((j: CandidatesFile | null) => setData(j))
      .catch(() => setData(null));
  }, []);

  // Pick mode: click anywhere → raycast against the whole scene → anchor point.
  const handlePointerDown = (e: { clientX: number; clientY: number }) => {
    if (!pickMode) return;
    const rect = gl.domElement.getBoundingClientRect();
    const ndc = new THREE.Vector2(
      ((e.clientX - rect.left) / rect.width) * 2 - 1,
      -((e.clientY - rect.top) / rect.height) * 2 + 1,
    );
    const raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(ndc, camera);
    const hits = raycaster.intersectObjects(scene.children, true);
    if (hits.length > 0) {
      const p = hits[0].point;
      setAnchor([Number(p.x.toFixed(2)), Number(p.y.toFixed(2)), Number(p.z.toFixed(2))]);
      setPickMode(false);
    }
  };

  const downloadAnchor = () => {
    if (!anchor) return;
    const blob = new Blob([JSON.stringify({ version: 1, point: anchor }, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'base-anchor.json';
    a.click();
    URL.revokeObjectURL(url);
  };

  // Build the world-space markers once per data load (positions are
  // refreshed per frame below via useFrame).
  const [markers] = useState(() => new Map<string, THREE.Object3D[]>());
  useEffect(() => {
    markers.clear();
    if (!data || !group) return;
    for (const part of data.parts) {
      const metaIdx = STL_META.findIndex((m) => m.file === part.filename);
      if (metaIdx < 0) continue;
      const objs: THREE.Object3D[] = [];
      for (const c of part.candidates) {
        const color = PALETTE[c.id % PALETTE.length];
        const sphere = new THREE.Mesh(
          new THREE.SphereGeometry(Math.max(c.radius * 0.35, 1.2), 12, 12),
          new THREE.MeshBasicMaterial({ color, transparent: true, opacity: 0.85, depthTest: false }),
        );
        const label = labelSprite(String(c.id), color);
        const holder = new THREE.Group();
        holder.add(sphere);
        label.position.set(0, Math.max(c.radius * 0.35, 1.2) + 4, 0);
        holder.add(label);
        // Render order so labels stay readable.
        sphere.renderOrder = 999;
        label.renderOrder = 1000;
        objs.push(holder);
        group.add(holder);
      }
      markers.set(part.filename, objs);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, group]);

  useFrame(() => {
    if (!data || !group) return;
    const s = stlScaleRef?.current ?? 1;
    const jawOpen = (1 - gripper / 100) * 10;
    const temp = new THREE.Matrix4();
    for (const part of data.parts) {
      const metaIdx = STL_META.findIndex((m) => m.file === part.filename);
      if (metaIdx < 0) continue;
      const meta = STL_META[metaIdx];
      const jointIdx = meta.parentJoint >= 0 ? meta.parentJoint : frames.length - 1;
      const pose = frames[jointIdx];
      if (!pose) continue;
      const objs = markers.get(part.filename);
      if (!objs) continue;
      const cal =
        calibrationOverridesRef?.current.get(meta.file) ??
        calibrationConfigRef?.current.get(meta.file) ??
        new THREE.Matrix4().identity();
      for (let i = 0; i < objs.length; i++) {
        const c = part.candidates[i];
        // world = F × jaw × scale × cal × center
        temp.compose(
          new THREE.Vector3(...pose.pos),
          new THREE.Quaternion(...pose.quat),
          new THREE.Vector3(1, 1, 1),
        );
        if (meta.jawDirection !== 0 && jawOpen !== 0) {
          temp.multiply(new THREE.Matrix4().makeTranslation(0, meta.jawDirection * jawOpen, 0));
        }
        temp.multiply(new THREE.Matrix4().makeScale(s, s, s));
        temp.multiply(cal);
        const p = new THREE.Vector3(...c.center).applyMatrix4(temp);
        objs[i].position.copy(p);
      }
    }
  });

  if (!data) return null;
  return (
    <group
      ref={(g) => {
        if (g && !group) setGroup(g);
      }}
    >
      {/* Pick-mode anchor marker + UI */}
      <mesh
        visible={false}
        onPointerDown={(e) => handlePointerDown(e.nativeEvent)}
        // An invisible full-scene receiver so the pick works from any angle.
        renderOrder={-1}
      >
        <boxGeometry args={[10000, 10000, 10000]} />
        <meshBasicMaterial visible={false} />
      </mesh>
      {anchor && (
        <mesh position={anchor}>
          <sphereGeometry args={[4, 16, 16]} />
          <meshBasicMaterial color="#ff00ff" transparent opacity={0.9} depthTest={false} />
        </mesh>
      )}
      <Html position={[0, 0, 0]} style={{ pointerEvents: 'none' }}>
        <div style={{ position: 'absolute', top: -120, left: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
          <button
            onClick={() => setPickMode((v) => !v)}
            style={{ pointerEvents: 'auto', background: pickMode ? '#f0f' : '#333', color: '#fff', border: '1px solid #666', borderRadius: 4, padding: '4px 8px', fontSize: 11, cursor: 'pointer' }}
          >
            {pickMode ? '● Click the base hole…' : 'Pick base anchor'}
          </button>
          {anchor && (
            <>
              <span style={{ background: '#222', padding: '2px 6px', borderRadius: 4, fontSize: 10, color: '#f0f' }}>
                anchor ({anchor.join(', ')}) mm
              </span>
              <button
                onClick={downloadAnchor}
                style={{ pointerEvents: 'auto', background: '#333', color: '#fff', border: '1px solid #666', borderRadius: 4, padding: '2px 8px', fontSize: 11, cursor: 'pointer' }}
              >
                 Download anchor.json
              </button>
            </>
          )}
        </div>
      </Html>
    </group>
  );
}
