/**
 * END-TO-END DRAWING TEST: gcode → IK → serial protocol → geometry.
 *
 * Follows the exact production pipeline the web app uses:
 *   1. Parse a real gcode file (`parseGcode`).
 *   2. Resolve it through the REAL IK (wasm `solveDrawingPlaneIk`).
 *   3. Serialize the plan through the v2 serial protocol (`buildManifest` →
 *      `SAMPLE q1..q6 dtUs` lines — the exact wire contract the firmware
 *      receives, with integer-µs quantization).
 *   4. Reconstruct what the robot would ACTUALLY draw: parse the protocol
 *      lines back to servo µs (as the firmware would), convert µs → q → FK
 *      (tool tip positions), keep the samples on the drawing plane.
 *   5. Assert the reconstructed drawing matches the intended shape.
 *
 * This measures how much error the IK + protocol introduce end to end: if
 * the reconstruction deviates beyond the bound, the shape error comes from
 * the IK resolution / quantization — if it stays tight, the physical wobble
 * must come from the mechanics (backlash, servo, stiffness).
 *
 * The wasm build (`web/src/pkg`, generated by `npm run wasm`) is required;
 * if absent the suite skips with a warning.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import init from '../pkg/bombolab_wasm';
import { fabriCreator, forwardKinematics, solveDrawingPlaneIk } from '../wasm';
import { parseGcode } from './gcode';
import { planTimeline, type PlanSample } from './planTimeline';
import { buildManifest, validateManifest } from './manifest';
import { ikPathFromSamples, maxDeviationToPath } from './fkPath';
import type { RobotDef } from '../kinematics/types';

// skipIf is evaluated at COLLECTION time, so the skip decision must be a
// synchronous file-existence check, not a value set in async beforeAll.
const WASM_FILE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'pkg',
  'bombolab_wasm_bg.wasm',
);
const wasmFileExists = existsSync(WASM_FILE);

beforeAll(async () => {
  if (!wasmFileExists) return;
  try {
    const bytes = readFileSync(WASM_FILE);
    try {
      await init(bytes);
    } catch {
      // Older wasm-bindgen glue: accept a pre-compiled module instead.
      await init(new WebAssembly.Module(bytes));
    }
    console.log('[e2eDrawing] wasm inicializado OK');
  } catch (err) {
    console.warn('[e2eDrawing] wasm init FALLÓ:', (err as Error)?.message ?? err);
  }
});

/** Closed 50×50 mm square centered at (200, 0), drawing plane z=80. */
const SQUARE_GCODE = [
  'G21',
  'G90',
  'G0 X175 Y-25 Z120',
  'G0 X175 Y-25 Z80',
  'G1 X225 Y-25 F2400',
  'G1 X225 Y25',
  'G1 X175 Y25',
  'G1 X175 Y-25',
].join('\n');

/** Ideal square corners in drawing order (DH coords). */
const SQUARE_CORNERS: [number, number][] = [
  [175, -25],
  [225, -25],
  [225, 25],
  [175, 25],
  [175, -25],
];

/** Ideal square polyline in three.js coords (same space as ikPathFromSamples). */
function squareReference(): [number, number, number][] {
  return SQUARE_CORNERS.map(([x, y]) => [x, 80, y]);
}

function makeRobot(): RobotDef {
  return fabriCreator();
}

/** FK the robot's home pose → start TCP for planTimeline. */
function homeTcp(robot: RobotDef): [number, number, number] {
  const fk = forwardKinematics(robot.segments, robot.baseTransform, robot.toolTransform);
  return [fk.ee[3], fk.ee[7], fk.ee[11]];
}

/**
 * Run the full pipeline and return { plan, protocolSamples, drawn } where
 * `drawn` is the protocol round-tripped drawing path (three.js coords).
 */
function runPipeline(robot: RobotDef, smooth: boolean) {
  const parsed = parseGcode(SQUARE_GCODE, { planeZ: 80, travelZ: 120, autofit: false });
  const samples = planTimeline(parsed.commands, {
    ik: solveDrawingPlaneIk,
    robot,
    startQ: robot.segments.map((s) => s.q),
    gripperPct: 0,
    startTcp: homeTcp(robot),
    smooth,
  });

  const manifest = buildManifest(samples);
  if (manifest instanceof Error) throw manifest;

  // Protocol round-trip: parse every SAMPLE line exactly as the firmware
  // would — integer µs + dtUs. penDown is NOT on the wire, so the drawing
  // split falls back to the z≈plane heuristic (physics: the pen only marks
  // paper on the plane).
  const protocolSamples: PlanSample[] = [];
  let t = 0;
  for (const line of manifest.lines) {
    const m = /^SAMPLE ((?:\d+ ){5}\d+) (\d+)$/.exec(line);
    if (!m) throw new Error('línea SAMPLE inválida: ' + line);
    const q_us = m[1].split(' ').map(Number);
    const dtUs = Number(m[2]);
    protocolSamples.push({ t, q_us, count: 1 });
    t += dtUs / 1e6;
  }

  const drawn = ikPathFromSamples(robot, protocolSamples, 80).drawing;
  return { samples, manifest, protocolSamples, drawn };
}

/** Minimum distance from point p to any point in points. */
function minDistToPoints(
  p: [number, number, number],
  points: [number, number, number][],
): number {
  let best = Infinity;
  for (const q of points) {
    const d = Math.hypot(p[0] - q[0], p[1] - q[1], p[2] - q[2]);
    if (d < best) best = d;
  }
  return best;
}

describe('E2E dibujo: gcode → IK → protocolo → geometría', () => {
  it.skipIf(!wasmFileExists)(
    'dibuja el cuadrado cerrado con desvío ≤ 2.0 mm y alcanza las 4 esquinas',
    () => {
      const robot = makeRobot();
      const { manifest, protocolSamples, drawn } = runPipeline(robot, false);

      // Protocol validity: the exact lines the firmware validates.
      const valid = validateManifest(manifest.lines);
      expect(valid).not.toBeInstanceOf(Error);
      expect((valid as { count: number }).count).toBe(manifest.count);
      expect(manifest.count).toBeGreaterThan(0);

      // Dense coverage: enough drawing samples to trace all 4 edges.
      expect(drawn.length).toBeGreaterThan(50);

      // Shape fidelity: every reconstructed drawing point stays close to
      // the ideal closed square.
      const ref = squareReference();
      const dev = maxDeviationToPath(drawn, ref);
      expect(
        dev,
        `desvío máx del cuadrado (IK + protocolo): ${dev.toFixed(3)} mm`,
      ).toBeLessThanOrEqual(2.0);

      // Every corner is actually reached by the commanded frames.
      for (const [x, y] of SQUARE_CORNERS) {
        const d = minDistToPoints([x, 80, y], drawn);
        expect(
          d,
          `esquina (${x}, ${y}) alcanzada: ${d.toFixed(3)} mm`,
        ).toBeLessThanOrEqual(2.0);
      }

      // Sanity: the protocol path is consistent with the direct plan path.
      expect(protocolSamples.length).toBeGreaterThan(0);
      expect(protocolSamples[0].q_us).toHaveLength(6);
    },
  );

  it.skipIf(!wasmFileExists)(
    'el suavizado no degrada la forma (desvío ≤ crudo + 1.0 mm)',
    () => {
      const robot = makeRobot();
      const raw = runPipeline(robot, false);
      const smooth = runPipeline(robot, true);

      const ref = squareReference();
      const devRaw = maxDeviationToPath(raw.drawn, ref);
      const devSmooth = maxDeviationToPath(smooth.drawn, ref);

      expect(
        devSmooth,
        `desvío crudo ${devRaw.toFixed(3)} mm → suavizado ${devSmooth.toFixed(3)} mm`,
      ).toBeLessThanOrEqual(devRaw + 1.0);

      // Smoothing must still respect the shape bound.
      expect(devSmooth).toBeLessThanOrEqual(2.5);
    },
  );
});
