[package]
name = "bombolab-core"
version = "0.1.0"
edition = "2024"
description = "Core data model and kinematics for Bombolab"
license = "MIT"

[[bin]]
name = "dh-solve"
path = "src/bin/dh-solve.rs"

[[bin]]
name = "quaternion-solve"
path = "src/bin/quaternion-solve.rs"

[[bin]]
name = "serial-test"
path = "src/bin/serial-test.rs"

[[bin]]
name = "ik-solve"
path = "src/bin/ik-solve.rs"

[[bin]]
name = "draw-path"
path = "src/bin/draw-path.rs"

[dependencies]
nalgebra = "0.35.0"
serialport = "4"
ctrlc = "3"
